# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('sex', models.CharField(choices=[('M', '\u7537'), ('F', '\u5973')], max_length=1)),
                ('birthday', models.CharField(max_length=32)),
                ('grade', models.IntegerField()),
                ('class_num', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=32)),
                ('college', models.CharField(max_length=128)),
                ('major', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=128)),
                ('qq_num', models.CharField(blank=True, max_length=16, null=True)),
                ('wx_num', models.CharField(blank=True, max_length=128, null=True)),
                ('can_long_distance_relationship', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
